export { default as Home } from './Home'
export { default as WhoWeAre } from './WhoWeAre'
export { default as OurProduct } from './OurProduct'
export { default as Contact } from './Contact'
export { default as Faqs } from './Faqs'
export { default as HelpCenter } from './HelpCenter'
export { default as TermsAndCondition } from './TermsAndCondition'
export { default as PrivacyPolicy } from './PrivacyPolicy'

export { default as Login } from './auth/Login'
export { default as ForgetPassword } from './auth/ForgetPassword'
export { default as PasswordResetConfirm } from './auth/PasswordResetConfirm'
export { default as Register } from './auth/Register'
export { default as Profile } from './auth/Profile'

export { default as GetDeliveryRequests } from './deliveryRequests/GetDeliveryRequests'
export { default as GetDeliveryRequestDetails } from './deliveryRequests/GetDeliveryRequestDetails'
export { default as AddDeliveryRequest } from './deliveryRequests/AddDeliveryRequest'

export { default as Dashboard } from './Dashboard'