export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Faqs } from './Faqs'
export { default as Jumbotron } from './Jumbotron'
export { default as Sidebar } from './Sidebar'
export { default as RiderBookingPayment } from './RiderBookingPayment'